"""empty message

Revision ID: 852897f6f9af
Revises: 
Create Date: 2021-06-01 22:13:45.947015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852897f6f9af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=True),
    sa.Column('name_kor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('crypto_ticker', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_ticker'], ['crypto.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('crypto')
    # ### end Alembic commands ###
